common: &common
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: shuttle
  password:
  pool: 50
  reconnect: true
  reaping_frequency: 30

development:
  <<: *common
  database: shuttle_development

test:
  <<: *common
  database: shuttle_test

staging:
  <<: *common
  database: shuttle_staging

production:
  <<: *common
  database: shuttle_production
